# Generated by Django 5.2 on 2025-04-24 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cooking_time', models.IntegerField(help_text='Time in minutes')),
                ('ingredients', models.TextField(help_text='Comma-separated list of ingredients')),
                ('description', models.TextField(blank=True)),
                ('difficulty', models.CharField(max_length=10)),
            ],
        ),
    ]
